### ISSUE TITLE
依頼　フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sontixyou** [sontixyou/furima-33852#11]
アプリURL
https://furima-33852.herokuapp.com/

Basic認証
ID　admin
Pass 222222

出品者用
メールアドレス   test1@test.com
パスワード           111111a

購入者用
メールアドレス   test2@test.com
パスワード           222222a

**Comment by MakiTaka** [comment]
@sontixyou さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
・購入用カードの番号・期限・セキュリティコードの記載がなかったため、
購入機能の確認ができておりません。
お手数ですがご教授いただけますと幸いです。

・投稿した画像がS3に反映されていないようです。
ご確認いただけますと幸いです。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sontixyou** [comment]
・クレジットカードの情報です
購入用カードの番号  4242424242424242
期限 5月　26年
セキュリティコード  123
・投稿した画像がS3に保存されるように変更しました。

**Comment by MakiTaka** [comment]
@sontixyou さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・商品を本番環境で購入できるかどうかの確認をお願いします。
現在正しいカード情報、住所でも購入ができず、「Token can't be blank」と出てしまいます。

※S3は正常に変更されていました。
修正ありがとうございます！

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sontixyou** [comment]
購入機能で編集したコードが未反映でした。お手数ですが、再度レビュお願いいたします

**Comment by kubota-tec** [comment]
@sontixyou さん、修正、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品情報編集機能**
`ログイン状態の出品者であっても、URLを直接入力して自身の売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること`
→現在売却済みの商品でも編集ページへ遷移が可能です。

**商品詳細表示機能**
`商品が出品されていない状態では、ダミーの商品情報が表示されること`
→こちら現在確認ができておりません。恐れ入りますが、画像を含むデータを全てリセットしてから再度ご提出のほどよろしくお願いいたします。


※本番環境での購入はしっかりと確認できました！
修正ありがとうございます！

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kubota-tec** [comment]
@sontixyou さん、修正、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。
